package com.wenge.gov.common.model.po;

import com.wenge.gov.common.model.po.base.BaseIdcard;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Idcard extends BaseIdcard<Idcard> {
	
}
