package com.wenge.gov.common.model.po;

import com.wenge.gov.common.model.po.base.BasePassportInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PassportInfo extends BasePassportInfo<PassportInfo> {
	
}
