package com.wenge.gov.common.model.po;

import com.wenge.gov.common.model.po.base.BasePass;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Pass extends BasePass<Pass> {
	
}
