package com.wenge.gov.common.model.po.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePass<M extends BasePass<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public void setSurname(java.lang.String surname) {
		set("surname", surname);
	}
	
	public java.lang.String getSurname() {
		return getStr("surname");
	}

	public void setGivenname(java.lang.String givenname) {
		set("givenname", givenname);
	}
	
	public java.lang.String getGivenname() {
		return getStr("givenname");
	}

	public void setSex(java.lang.String sex) {
		set("sex", sex);
	}
	
	public java.lang.String getSex() {
		return getStr("sex");
	}

	public void setDestination(java.lang.String destination) {
		set("destination", destination);
	}
	
	public java.lang.String getDestination() {
		return getStr("destination");
	}

	public void setBirth(java.lang.String birth) {
		set("birth", birth);
	}
	
	public java.lang.String getBirth() {
		return getStr("birth");
	}

	public void setExpiry(java.lang.String expiry) {
		set("expiry", expiry);
	}
	
	public java.lang.String getExpiry() {
		return getStr("expiry");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public void setInsertTime(java.util.Date insertTime) {
		set("insert_time", insertTime);
	}
	
	public java.util.Date getInsertTime() {
		return get("insert_time");
	}

}
