package com.wenge.gov.common.model.po.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePassportInfo<M extends BasePassportInfo<M>> extends Model<M> implements IBean {

	public void setPid(java.lang.String pid) {
		set("pid", pid);
	}
	
	public java.lang.String getPid() {
		return getStr("pid");
	}

	public void setCountryCode(java.lang.String countryCode) {
		set("country_code", countryCode);
	}
	
	public java.lang.String getCountryCode() {
		return getStr("country_code");
	}

	public void setSurname(java.lang.String surname) {
		set("surname", surname);
	}
	
	public java.lang.String getSurname() {
		return getStr("surname");
	}

	public void setGivenname(java.lang.String givenname) {
		set("givenname", givenname);
	}
	
	public java.lang.String getGivenname() {
		return getStr("givenname");
	}

	public void setSex(java.lang.String sex) {
		set("sex", sex);
	}
	
	public java.lang.String getSex() {
		return getStr("sex");
	}

	public void setBirthDate(java.lang.String birthDate) {
		set("birth_date", birthDate);
	}
	
	public java.lang.String getBirthDate() {
		return getStr("birth_date");
	}

	public void setExpiryDate(java.lang.String expiryDate) {
		set("expiry_date", expiryDate);
	}
	
	public java.lang.String getExpiryDate() {
		return getStr("expiry_date");
	}

	public void setIssueDate(java.lang.String issueDate) {
		set("issue_date", issueDate);
	}
	
	public java.lang.String getIssueDate() {
		return getStr("issue_date");
	}

	public void setBirthPlace(java.lang.String birthPlace) {
		set("birth_place", birthPlace);
	}
	
	public java.lang.String getBirthPlace() {
		return getStr("birth_place");
	}

	public void setIssuePlace(java.lang.String issuePlace) {
		set("issue_place", issuePlace);
	}
	
	public java.lang.String getIssuePlace() {
		return getStr("issue_place");
	}

	public void setType(java.lang.String type) {
		set("type", type);
	}
	
	public java.lang.String getType() {
		return getStr("type");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public void setInsertTime(java.util.Date insertTime) {
		set("insert_time", insertTime);
	}
	
	public java.util.Date getInsertTime() {
		return get("insert_time");
	}

}
